# Specify the language/environment
language: minimal

# Use Docker services
services:
  - docker
jobs:
  include:
    - stage: build
      name: Build Docker Image
      script:
        # Navigate to the cloned private repo and build the Docker image
        - cd tikton
        - docker build -t app1:latest .



