language: bash

services:
  - docker

before_install:
  # Start Minikube and configure Docker to use Minikube’s Docker daemon
  - minikube start --driver=docker
  - eval $(minikube -p minikube docker-env)

  # Build Docker image for the application using Minikube's Docker daemon
  - docker build -t sample-docker-react  .

deploy:
  # Deploy to Minikube
  provider: script
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
  on:
    branch: master
