version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
        environment:
          NODE_ENV: development
      - image: circleci/python:3.8
        environment:
          TESTING: true

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Docker Image
          command: docker build -t sample-docker-react  .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
