apiVersion: v1
kind: Service
metadata:
  name: sample-docker-react-service
spec:
  type: NodePort
  selector:
    app: sample-docker-react
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30036  # Minikube will expose the service on this port